steps:
  #unit test the dags 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/leah-playground/cicd:latest', '.']
    id: 'docker build'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/leah-playground/cicd:latest']
    id: 'docker push'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/leah-playground/cicd:latest']
    id: 'docker pull'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-it', 'gcr.io/leah-playground/cicd:latest']
    id: 'test-dags'
  #update the composer environment
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['composer', 'environments', 'update', 'cloudbuild-demo', '--update-pypi-packages-from-file', 'requirements-composer.txt', '--location', 'us-west4']
    id: 'update-composer-env'
timeout: 3600s