steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['composer', 'environments', 'update', 'cloudbuild-demo', '--update-pypi-packages-from-file', 'requirements-composer.txt', '--location', 'us-central1']
timeout: 3600s
